### ISSUE TITLE
Prevent Censorship Attacks on Tabulation Mechanism

### ISSUE THREAD

**Issue by lkngtn** [HiveCommons/Hive-Democracy#3]
Allowing chains of infinite length means that it may not be feasible to tabulate votes within acceptable time/cost constraints. Therefore, we need to limit the length of delegation chains during the tabulation of votes. 

Cost/Time of tabulation is related to the chain depth and the number of voters. There are two primary attack vectors that should be considered that would prevent us from tabulating votes. 

1. A malicious actor might create many accounts with small weight and vote -- They would pay the gas price for each vote but could prevent the tabulation mechanism to complete within time/cost constraints. 

2. A malicious actor might construct excessively long delegation chains. Rather than needing additional stake spread across many accounts, they could have many accounts with no stake but delegate votes down a very long chain. Again the attacker may need to pay a significant amount in gas, but they could prevent the tabulation mechanism from completing within time/cost constraints. 

**To mitigate these attacks we should do the following:**

Minimum Balance (b) 
Maximum Depth (d)
Token Supply (s)

For a desired worst case time/cost constraint (in terms of iterations) we can calculate what those values should be based on the equation. 

iterations = s/b * d
iterations * cost/time per iteration = total cost/time

**Comment by lkngtn** [comment]
If we find that we can move some of the tabulation off-chain we should be able to support smaller minimum balances and/or longer delegation chains.

**Comment by lkngtn** [comment]
While we do not want to lock token balances, so we cannot guarantee that a minimum balance is retained after initially voting, we can stop processing a delegation chain if one of the nodes does not have the minimum balance.

**Comment by 3esmit** [comment]
There will be a inchain restriction on delegating in a too far away delegation chain, because when you call delegate() function, inside it checks if there is a circular delegation, so it goes till the end of chain to find which is the final delegate, but still a vector of this issue.
The other problem is that a delegate can have many delegators, and this also consumes lots of gas.
Some contracts implement a option where you can call multiple times a function to finish the result, but in our case this is difficult because the function use recursive calls and continuing from where paused might be tricky. There is also the gas impact in the function, that would be havier but accept resume from out-of-gas. I will study this option and see if there is a way.

The best option is offchain, that would also tabualate all votes at the end, so everyone can change the delegator and vote byself until blockEnd. This helps solving the bad delegator problem.

**Comment by 3esmit** [comment]
By the way, your ideas are great about mitigation of attacks, I will study to implement those too in the "delegate(address)" function.

**Comment by timschloe** [comment]
Ehm, again, sorry for being naive and heretic, but I don't think circular delegation is a problem. It will remain with the default (abstain) until one of the circle-elements changes their delegation and actually casts a vote. Then all others follow. What's the problem exactly?

About the many small accounts: I guess for voting a minimal value of the coin can be significantly larger than a "Satoshi"" - I fail to imagine a scenario where the same voting system needs to process votes differing by a factor of 10^9...? While not necessarily solving the issue, a larger minimal coin split should at least help mitigate.

**Comment by lkngtn** [comment]
I don't think circular delegation is inherently a problem, but it is not particularly efficient from a cost/scalability perspective, and in the context of doing tabulation on the chain that is a really big factor. 

Regarding the minimal value, ideally, we would not make it dependent on the coin divisibility as it nice if the system generalizable to any ERC20 token or at least any MiniMe token regardless of the tokens divisibility. A minimum balance for chain nodes seem reasonable, we can simply stop calculating down a chain if we reach a node with a balance below the minimum.

**Comment by 3esmit** [comment]
Circular delegation is impossible by design. Changing design to add this feature is not going to happen, but in case of change in delegation chain design we need to block it, so because of this its just blocked by default in current implementation aswell. 

The reason current design makes impossible to circle close a delegation chain is because it would run out of gas when trying to read delegate, that does not exist in a circular delegation chain.

The reason we should not allow a circular delegation is because they are a accidental case, and there is no use case where none wants to vote and all wants to delegate. The circular delegation is an accidental case that would break the voting process for the people wanting their voice to be heard, it's equivalent to delegating to an address controlled by "none". 
I don't see any vector of breaking voting by a circular delegation other then wasting the votes in that circular chain.

**Comment by lkngtn** [comment]
> The circular delegation is an accidental case that would break the voting process for the people wanting their voice to be heard 

I don't think this is strictly true. A Delegation loop could have some small amount of utility in the sense that a ring of people could all trust each other implicitly and if none feel comfortable making a decision and it defaults to "abstain", I don't see an inherent issue with this situation, assuming it doesn't occur accidentally. 

However, I agree that it has minimal utility and increases complexity and cost significantly so it seems prudent to simply prohibit it.
