### ISSUE TITLE
Implement Delegate Expiration

### ISSUE THREAD

**Issue by lkngtn** [HiveCommons/Hive-Democracy#6]
Liquid Delegation is intended to allow a community to balance direct and representative governance as needed, however, the expectation is that voters will actively participate and override their delegates as needed. 

A significant concern is if voters delegate their vote and then do not participate beyond that, in doing so they have created a super-delegate which has more weight and is not kept in line by the threat of the voter becoming more engaged and un-delegating their vote.

The significance of this effect is debatable, however, to mitigate this effect we could consider enforcing a delegation expiration where the delegation will automatically revoke after a certain period of inactivity. This seems like a healthy check to ensure a minimal amount of engagement on the part of voters and should reduce the impact of super-delegates becoming corrupt.

We should carefully consider this in terms of the additional cost and complexity to the system, and the expected social benefit. Would a separate off chain mechanism that reminded users to check on their delegates periodically be just as effective?

**Comment by 3esmit** [comment]
It might happen that user delegates and his votes are not even being used, or being used against user will.  
The problem of super-delegates is not a problem if the super-delegate is well behaving, because this vote centralization is not real, the delegate cannot control his power forever as his power mostly came from delegation, and possibly from other big delegates. 
The system must give options to escape from delegates that turn evil due personal interests, but should enable that delegates became powerful, because this is their influence. 
There might be subdelegations where some delegates have many power, but in others subdelegations the chain is different and the super-delegates will be different.
If we prevent super-delegates then we are preventing experts from having super-influence, in topics where few understand, but many trust them. 

The delegate expiration might be interesting for some use-case and with a big delay, such as 2 or 4 years, I guess for proof of aliveness? 

We can do the singatures offchain and require user entering some data only would know at present, such as use a near present blockhash in the signature, and the system uses that blockhash time as signature time for expiration.

**Comment by lkngtn** [comment]
Right, the goal isn't to prevent large delegates or influential delegates, but to mitigate the issue of a voter delegating their vote and then being completely disengaged, as it is important that they remain engaged in order to step in and override the delegate in the event of delegate defection. By introducing an expiration period we have some certainty that everyone who has delegated their vote has some minimum amount of engagement because they must reset the delegation or confirm it every so often. 

But I agree that this seems like a lower priority issue as I think that in the context of Stake-Based voting as opposed to one-person-one-vote the issue of people delegating and then disengaging completely would be less common.

**Comment by timschloe** [comment]
I think while low priority, the issue is interesting in terms of implications on the user interface design.

To me the natural approach would be to use nudging in the interface, not a fixed value. I'm thinking of an app interface that has a box where you can enter your delegation conditions, including the tags/topics delegated, the notification rules, and also an expiration date (in time or number of decisions). You can then nudge the user towards the option we think is preferable (e.g. 2 years), but leave the decision space open between 0 and infinite.

Obviously, the default options in the standard delegation interface should also be something that can be changed by voting.

I wouldn't want to differentiate too much between stake-based and one-person-one-vote logic for now, as one-person-one-vote is simply a sub-set of stake-based, where stakes are bound to ID and non-transferable. Ideally Hive should work just fine no matter the distribution of tokens among individuals.

Btw. the more I think about it, the more interesting it seems to use "follow" instead of "delegate". Follow's don't even have to be saved on the chain, it should be enough if they are saved locally by the user, who can look up the votes of their "delegates" (the users they follow) on the chain. So no gas needed, if I'm not mistaken.

**Comment by 3esmit** [comment]
This makes reading the delegation chain more expansive in gas, since it includes one more storage read and more verifications, could double gas usage per delegation level.

The changes are "adding a field in delegation struct containing `uint expireblock` or `uint expiretime` and verifing them in the read of delegation chain, and not considering the expired ones.
expireblock is better because minime also works with block, but not a prboelm using expiretime if is is more important to use time. (storage and check is cost is the same)

**Comment by timschloe** [comment]
Any reason to store the expiration in the chain and not in the users App? App could just automatically withdraw when expiration time is reached, then it takes no more than delegating again.

**Comment by lkngtn** [comment]
> Any reason to store the expiration in the chain and not in the users App? App could just automatically withdraw when expiration time is reached, then it takes no more than delegating again.

This might work in a federated set up where the app is hosted, but if it is purely client side the client has to be connected for the expiration to have any effect -- since the point of it is to mitigate issues with inactive/unattentive voters relying on them to have a client connected seems counter-intuitive.

**Comment by timschloe** [comment]
I see the point. Are you saving the delegations with a timestamp by
default? The you could have a fixed expiration date of 2 years for those
who never log on again, and a client side expiration for those who don't.

There might also be other reasons for saving a timestamp, albeit I can't
think of any right now.

**Comment by timschloe** [comment]
For those who do I mean :-)

**Comment by lkngtn** [comment]
I think building expiration into the contracts themselves is probably a pretty low priority at this point, and client side tools for managing expiration could be created fairly easily if there is demand for that functionality.

**Comment by lkngtn** [comment]
The progress on Liquid Democracy in Aragon's [Liquid Democracy working group](https://docs.google.com/document/d/1fw_gpxaMsV-tJHpKz8jU22cciLBREQ5vB3T6nvvJbtU/edit#heading=h.jcmrpwsao2rg) is going well. Closing issues in this repo prior to archiving so that effort can be more easily coordinated in the working group.
